runtime: python39

handlers:
- url: /static
  static_dir: static

- url: /.*
  script: auto

entrypoint: gunicorn -b :$PORT application:app

env_variables:
  # Add any environment variables here
  # EXAMPLE: 
  # YOUR_VARIABLE_NAME: 'your_value'

automatic_scaling:
  target_cpu_utilization: 0.65
  min_instances: 1
  max_instances: 3
